---

- 
  name : A simple Play
  hosts : appgroup
  user : ansibleadm
  become : yes
  become_method : sudo


  tasks :
    - name : first task
      service : name=httpd enabled=true

    - name : second task 
      service : name=sshd enabled=true

...